### ISSUE TITLE
how to use mssql service from within app?

### ISSUE THREAD

**Issue by mhadi813** [alexpulver/cf-pyodbc#2]
Hi Alex,
Thank you publishing your code. I am trying to read and write pandas dataframe to azure sql server from pivotal python. the code runs fine on my laptop but when it is deployed on PCF, it throws error:
```
ERROR:root:('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
```
I understand that service binding with the app exposes connection input as env variables, but don't know how to create the connection. Thanks

**Comment by alexpulver** [comment]
Hi @mhadi813,

That code example is fairly old, so there might be changes in CF that might render it as not working. Having said that, I don't think there is something in the example (beyond old driver versions maybe) that shouldn't work even today. 

I would like to clarify one thing first - this example is intended to be run as a custom [Docker container on CF](https://docs.cloudfoundry.org/adminguide/docker.html), and not as the built-in CF Linux image. Did you check whether your code works by packaging it into the container and running the container locally as described in [README.md](https://github.com/alexpulver/cf-pyodbc/blob/master/README.md)?

**Comment by mhadi813** [comment]
Thanks @alexpulver for explaining. I'm new to docker, so couldn't tell whether I could use your code without docker. I finally ended up using apt and python buildpacks to install ms sql drivers and pyodbc.

**Comment by alexpulver** [comment]
First of all glad to hear you resolved this! Also, I think I confused you a bit - the local debugging should be done in Docker (because of various dependencies like FreeTDS that might not be available on your system). But the full code here **can** run as Python buildpack on CF Linux - that's where I was wrong in my previous comment. 

There are a few special files in the repository that allow all of this to work:

- `bin/post_compile` - this file is a hook recognized by Python buildpack that installs the FreeTDS driver after all Python packages have been installed. The reason it is done last, is because FreeTDS driver requires ODBC to be installed already - see `--with-odbc-nodm` parameter in the script. ODBC is installed as part of Python packages installation
- `environment.yml` - if present, Python buildpack will use [miniconda](https://docs.cloudfoundry.org/buildpacks/python/index.html#miniconda) instead of pip to install dependencies. This is useful when Python packages rely on compiled binaries that pip can't install - like ODBC in this case (if I remember correctly)
- `manifest.yml` - sets the environment variables that FreeTDS driver uses to locate ODBC configuration
- `runtime.txt` - if present, Python buildback uses the specified Python version for runtime environment
- `config/odbcinst.ini` - ODBC configuration used by FreeTDS driver as mentioned above. The driver uses `odbcinst.ini` name for lookup, so the file must be names exactly like this. You can see that driver location in the INI file has base directory of `/app/vendor`. This is where the `bin/post_compile` hook installs the driver to

Hope that makes sense now :).

**Comment by mhadi813** [comment]
Thank alot, this is super help.
